version: '2'

services:
  db:
    image: registry.centos.org/postgresql/postgresql:9.6
    ports:
      - "5434:5432"
    environment:
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
    networks:
      - default
  cluster:
    image: fabric8-services/fabric8-cluster:latest
    command: -config /usr/local/cluster/etc/config.yaml
    environment:
      CLUSTER_POSTGRES_HOST: db
    ports:
      - "8087:8087"
    networks:
      - default
    depends_on:
      - db
